# db_url = jdbc:mysql://localhost:3306/transaction_db?createDatabaseIfNotExist=true
# db_username = root
# db_password = admin

spring.datasource.url=jdbc:mysql://localhost:3306/transaction_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop

spring.application.name=demotransaction

SERVER.port = 9000